### ISSUE TITLE
Guard against crashes in docker list commands

### ISSUE THREAD

**Issue by s4ke** [neuroforgede/docker-engine-networks-exporter#2]
The docker container list command seems to not be atomic and crashes whenever the container is pruned during its runtime:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status

    response.raise_for_status()

  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/993075dc249f1533cf36f52a473838ab0dd26b67bc5559712a8aba697097e172/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/events-notifier/./network_exporter_prom.py", line 205, in <module>

    watch_networks()

  File "/opt/events-notifier/./network_exporter_prom.py", line 135, in watch_networks

    for container in client.containers.list(all=True):

  File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 988, in list

    containers.append(self.get(r['Id']))

  File "/usr/local/lib/python3.10/site-packages/docker/models/containers.py", line 924, in get

    resp = self.client.api.inspect_container(container_id)

  File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped

    return f(self, resource_id, *args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/docker/api/container.py", line 783, in inspect_container

    return self._result(

  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result

    self._raise_for_status(response)

  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status

    raise create_api_error_from_http_exception(e) from e

  File "/usr/local/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception

    raise cls(e, response=response, explanation=explanation) from e

docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/993075dc249f1533cf36f52a473838ab0dd26b67bc5559712a8aba697097e172/json: Not Found ("No such container: 993075dc249f1533cf36f52a473838ab0dd26b67bc5559712a8aba697097e172")
```

We should the script resilient against this as well as the same case for networks - we already did this for services.

**Comment by s4ke** [comment]
Not doing it for networks for now. docker client has an option to ignore failures via `ignore_removed`
